services:
  shareit-server:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    # ТОЛЬКО дополнительные настройки, профиль уже в Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres




